[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://emilist.netlify.app/api"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 