[build]
  command = "npm run build && cp -r public/* .next/"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Serve JavaScript files with the correct MIME type
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

# These redirects are required for Next.js routing to work properly
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true
